# Generated by Django 2.2 on 2020-08-23 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatifi', '0003_auto_20200823_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='Parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatifi.Tweet'),
        ),
    ]
